<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{ifset $title}{$title} - {/if}ormion</title>
</head>

<body>
	{if $flashes}
		<p n:foreach="$flashes as $flash">{$flash->message}</p>
		<hr>
	{/if}

	<p>
		<a href="{plink Homepage:}">Home</a> |
		{foreach $pages as $page}
		<a href="{plink Page: $page->id}">{$page->name}</a> |
		{/foreach}
		<a href="{plink Page:add}">Add page</a>
	</p>

	<hr>

	@{include #content}
</body>
</html>
